[tool.poetry]
name = "mbta-slow-zone-bot"
version = "0.2.3"
description = "A Twitter/Mastodon/Slack bot to track MBTA slow zones"
authors = ["TransitMatters Labs Team"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.12"
boto3 = "^1.34.131"
tweepy = "^4.14.0"
"Mastodon.py" = "^1.8.1"
argparse = "^1.4.0"
datadog_lambda = "6.98.0"

[tool.poetry.dev-dependencies]
pip = ">=24.0"
chalice = "^1.31.2"
flake8 = "^7.1.1"
black = "^24.8.0"

[tool.black]
line-length = 120
target-version = ['py312']

[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"
